### ISSUE TITLE
This has an error

### ISSUE THREAD

**Issue by 2429581027** [mks0601/PoseFix_RELEASE#13]
Thank you very much for this work, I have a question and hope to get some help.
when I run the code `python test.py --gpu 0,1 --test_epoch 140`
There  is a erro

```
Process Worker-1:
Traceback (most recent call last):
  File "/opt/conda/envs/tensorflow/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/share8t/work/ZHR/POSE_ROOT/main/../lib/tfflat/mp_utils.py", line 34, in run
    msg = self._func(self.id, *self.args, **self.kwargs)
  File "test.py", line 202, in func
    range = [ranges[gpu_id], ranges[gpu_id + 1]]
IndexError: list index out of range
Traceback (most recent call last):
  File "test.py", line 233, in <module>
    test(int(args.test_epoch))
  File "test.py", line 206, in test
    result = MultiGPUFunc.work()
  File "/share8t/work/ZHR/POSE_ROOT/main/../lib/tfflat/mp_utils.py", line 82, in work
    id, msg = load_pkl( 'tmp_result_{}'.format(self._proc_ids[i]) )
  File "/share8t/work/ZHR/POSE_ROOT/main/../lib/tfflat/serialize.py", line 68, in load_pkl
    with open('{}.pkl'.format(name), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp_result_0.pkl'
```

**Comment by mks0601** [comment]
How many GPU do you have?

**Comment by 2429581027** [comment]
Thank you very much for your reply. I am sorry that I have not been able to respond to you in time. I have four GPUs. I don't know what went wrong. I use two other methods to generate json files, one of which puts input_pose to run normally, and the other one will get this error.and I found another error 
```
Process Worker-2:
Traceback (most recent call last):
  File "/opt/conda/envs/tensorflow/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/share8t/work/ZHR/POSE_ROOT/main/../lib/tfflat/mp_utils.py", line 34, in run
    msg = self._func(self.id, *self.args, **self.kwargs)
  File "test.py", line 202, in func
    range = [ranges[gpu_id], ranges[gpu_id + 1]]
IndexError: list index out of range
```

**Comment by mks0601** [comment]
Do you use COCO dataset? Can you print `len(ranges)`?

**Comment by 2429581027** [comment]
Yes, I am using the json file generated by val2017 in AlphaPose. And I don't know how to print len(ranges), thank you very much for your guidance. Since I just came into contact with this subject, my foundation is still very weak. I feel that I need to learn a lot of relevant knowledge and change a lot of things in order to make my json can be used. I have to express my gratitude to you again, and we have learned a lot of valuable knowledge because of the excellent work of you and the people like you.

**Comment by AnasArram** [comment]
I have the same error. i have 2 gpus but i run on one only. the len(ranges) is 1. Any suggestions?

**Comment by mks0601** [comment]
len(ranges) is ok. Please prepare input_pose correctly

**Comment by AnasArram** [comment]
I used your Testing result on the COCO 2017  as an input_pose. should that be okay?

**Comment by mks0601** [comment]
What do you mean by 'my' testing result? Also, did you correctly set `testset` in `config.py`?

**Comment by AnasArram** [comment]
i downloaded this results that you uploaded:
Testing result on the COCO 2017 training set of TF-SimpleHumanPose [kps].
In config.py i set the  testset = 'val' . as i am using the val dataset only.

**Comment by mks0601** [comment]
Please read README correctly. What you downloaded is testing result on training set and what you need is testing result on val set.

**Comment by gongzaizhou** [comment]
Can you provide 'person_keypoints_test-dev2017_Simple152_results.json'?

**Comment by mks0601** [comment]
I did't save the test result file.

**Comment by YJLeonMan** [comment]
when I run the code python test.py --gpu 0,1 --test_epoch 140  I have an error like this:
C:\Anaconda3\python3.exe G:/PoseFix_RELEASE-master/main/test.py --gpu 0 --test_epoch 140
loading annotations into memory...
Done (t=0.29s)
creating index...
index created!
Traceback (most recent call last):
  File "G:/PoseFix_RELEASE-master/main/test.py", line 231, in <module>
    test(int(args.test_epoch))
  File "G:/PoseFix_RELEASE-master/main/test.py", line 204, in test
    result = MultiGPUFunc.work()
  File "G:\PoseFix_RELEASE-master\lib\tfflat\mp_utils.py", line 65, in work
    p.start()
  File "C:\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'test.<locals>.func'

Process finished with exit code 1

Can You Help Me!! Thank You !!

**Comment by mks0601** [comment]
Actually, this code is only tested under multi-GPU setting. It seems you are using single GPU :(
