### ISSUE TITLE
something wrong with train

### ISSUE THREAD

**Issue by zhyujing** [mks0601/PoseFix_RELEASE#14]

**Comment by zhyujing** [comment]
Thank you for your great work, I have some question shown below, and I downloaded the .json from the COCO official website, but it seems to be wrong. Could you please tell me the reason? Thank you for your time!
Traceback (most recent call last):
  File "/home/ZYJ/PoseFix_RELEASE-master/main/train.py", line 30, in <module>
    trainer = Trainer(Model(), cfg)
  File "/home/ZYJ/PoseFix_RELEASE-master/main/../lib/tfflat/base.py", line 199, in __init__
    self._data_iter, self.itr_per_epoch = self._make_data()
  File "/home/ZYJ/PoseFix_RELEASE-master/main/../lib/tfflat/base.py", line 228, in _make_data
    test_on_trainset = json.load(f)
  File "/opt/anaconda3/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 15335425 (char 15335424)
