### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by zby-github** [mks0601/PoseFix_RELEASE#26]
The following error occurred when I was running train.py file. Please tell me how to solve it. Thank you very much.

cannot read train2017/000000179322.jpg
cannot read train2017/000000205086.jpg
cannot read train2017/000000274079.jpg
Process _Worker-2:
cannot read train2017/000000426975.jpg
cannot read train2017/000000328791.jpg
Process _Worker-3:
Process _Worker-4:
cannot read train2017/000000332096.jpg
Process _Worker-5:
cannot read train2017/000000390718.jpg
Process _Worker-6:
cannot read train2017/000000477774.jpg
Process _Worker-7:
cannot read train2017/000000512793.jpg
Process _Worker-8:
Process _Worker-10:
Process _Worker-9:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/share8t/work/POSE_ROOT-Posefix/main/../lib/tfflat/data_provider.py", line 207, in run
    dp = self.map_func(dp)
  File "/share8t/work/POSE_ROOT-Posefix/main/gen_batch.py", line 342, in generate_batch
    assert 0
Traceback (most recent call last):
AssertionError
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/share8t/work/POSE_ROOT-Posefix/main/../lib/tfflat/data_provider.py", line 207, in run
    dp = self.map_func(dp)
  File "/share8t/work/POSE_ROOT-Posefix/main/../lib/tfflat/data_provider.py", line 207, in run
    dp = self.map_func(dp)
  File "/share8t/work/POSE_ROOT-Posefix/main/gen_batch.py", line 342, in generate_batch
    assert 0
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/share8t/work/POSE_ROOT-Posefix/main/gen_batch.py", line 342, in generate_batch
    assert 0
  File "/share8t/work/POSE_ROOT-Posefix/main/../lib/tfflat/data_provider.py", line 207, in run
    dp = self.map_func(dp)
  File "/share8t/work/POSE_ROOT-Posefix/main/gen_batch.py", line 342, in generate_batch
    assert 0
AssertionError
AssertionError
AssertionError

**Comment by mks0601** [comment]
please place image files in correct directory

**Comment by zby-github** [comment]
Thank you very much

At 2019-09-09 20:27:55, "Gyeongsik Moon" <notifications@github.com> wrote:


please place image files in correct directory

**Comment by zby-github** [comment]
I still haven't solved the problem. I don't know what the name of the file should be.

Process _Worker-5:
cannot read train2017/000000260145.jpg
cannot read train2017/000000314904.jpg
cannot read train2017/000000401061.jpg
Process _Worker-6:
cannot read train2017/000000068812.jpg
Process _Worker-9:
Process _Worker-7:
Process _Worker-8:
Process _Worker-10:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/share8t/work/POSE_ROOT-Posefix/main/../lib/tfflat/data_provider.py", line 207, in run
    dp = self.map_func(dp)
  File "/share8t/work/POSE_ROOT-Posefix/main/gen_batch.py", line 343, in generate_batch
    assert 0
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/share8t/work/POSE_ROOT-Posefix/main/../lib/tfflat/data_provider.py", line 207, in run
    dp = self.map_func(dp)
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
AssertionError
  File "/share8t/work/POSE_ROOT-Posefix/main/gen_batch.py", line 343, in generate_batch
    assert 0
  File "/share8t/work/POSE_ROOT-Posefix/main/../lib/tfflat/data_provider.py", line 207, in run
    dp = self.map_func(dp)
  File "/share8t/work/POSE_ROOT-Posefix/main/gen_batch.py", line 343, in generate_batch
    assert 0
AssertionError
AssertionError
![1](https://user-images.githubusercontent.com/52476622/64576404-f6cc5c80-d3aa-11e9-9076-bd278f76980d.png)
![2](https://user-images.githubusercontent.com/52476622/64576413-fc29a700-d3aa-11e9-9522-c8dbeb36d9f4.png)

**Comment by zby-github** [comment]
Problem solved, thank you
