### ISSUE TITLE
Run nms on Windows 

### ISSUE THREAD

**Issue by AnasArram** [mks0601/PoseFix_RELEASE#9]
The nms library is created to work on linux only (so we have issues with cuda location etc). Any version of it may work on windows 10?

**Comment by mks0601** [comment]
Hi, actually, NMS is not important in the PoseFix if you can perform NMS for the initial pose estimation using any other pose estimator. The NMS is only used in test.py, so you can just remove it.

**Comment by AnasArram** [comment]
Okay thanks for quick respond.
Can you please give a brief description on how to use other pose estimators like tf-pose-estimator in this PoseFix?

**Comment by mks0601** [comment]
What do you mean by tf-pose-estimator? There is no guideline for other pose estimator. All you need is test result (.json file(s)) of any methods. Then, just feed .json file(s) to the PoseFix.

**Comment by AnasArram** [comment]
Thank you so much. i got this error now:

File "test.py", line 233, in <module>
    test(int(args.test_epoch))
  File "test.py", line 206, in test
    result = MultiGPUFunc.work()
  File "C:\Users\ANAS\Desktop\PoseFix_RELEASE-master\main\..\lib\tfflat\mp_utils.py", line 65, in work
    p.start()
  File "C:\Users\ANAS\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\ANAS\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\ANAS\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\ANAS\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\ANAS\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'test.<locals>.func'

(tensorflow) C:\Users\ANAS\Desktop\PoseFix_RELEASE-master\main>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ANAS\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\ANAS\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
--------------------------------------------

i just ran test.py and used your coco results as an input_pose.

**Comment by mks0601** [comment]
It seems there exist some issue for window machine like this [issue](https://github.com/matterport/Mask_RCNN/issues/93). Could you turn off multi process by `multi_thread_enable = False` in `config.py`? If available, I suggest you to use linux machine.

**Comment by AnasArram** [comment]
i just turned it off and ran again. still have the same issue!. Will try to find another solution, otherwise will run on linux machine.
